--Ben Kristofic, Ethan Pavolik CS 1555 Term Project
--FaceSpace
------------------------------------------
DROP TABLE USERS CASCADE CONSTRAINTS;
DROP TABLE FRIENDSHIPS CASCADE CONSTRAINTS;
DROP TABLE GROUPS CASCADE CONSTRAINTS;
DROP TABLE GROUP_MEMBERS CASCADE CONSTRAINTS;
DROP TABLE MESSAGES CASCADE CONSTRAINTS;
PURGE RECYCLEBIN;
-------------------------------------------

CREATE TABLE USERS (
	USER_ID NUMBER(10) PRIMARY KEY,
	F_NAME VARCHAR(32),
	L_NAME VARCHAR(32),
	EMAIL VARCHAR(32),
	BIRTH TIMESTAMP,
	LAST_LOGIN TIMESTAMP
);

CREATE TABLE FRIENDSHIPS (
	FRIENDSHIP_ID NUMBER(10) PRIMARY KEY,
	USER_ID1 NUMBER(10),
	USER_ID2 Number(10),
	FRIEND_STATUS NUMBER(1) DEFAULT 0,
	DATE_ESTABLISHED TIMESTAMP,		
	CONSTRAINT FK_USER1 FOREIGN KEY (USER_ID1) REFERENCES USERS (USER_ID),
	CONSTRAINT FK_USER2 FOREIGN KEY (USER_ID2) REFERENCES USERS (USER_ID)
);  

CREATE TABLE GROUPS (
	GROUP_ID NUMBER(10) PRIMARY KEY,
	NAME VARCHAR(32),
	DESCRIPTION VARCHAR(1024),
	MEMBER_LIMIT NUMBER(10)
);

CREATE TABLE GROUP_MEMBERS (
	GROUP_NUMBER_ID NUMBER(10),
	USER_ID NUMBER(10),
	GROUP_ID NUMBER(10),
	CONSTRAINT FK_GROUP_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID),
	CONSTRAINT FK_GROUP_GROUP_ID FOREIGN KEY (GROUP_ID) REFERENCES GROUPS (GROUP_ID)
);

CREATE TABLE MESSAGES (
	MESSAGE_ID NUMBER(10) PRIMARY KEY,
	SUBJECT VARCHAR(32),
	BODY VARCHAR(100),
	SENDER_ID NUMBER(10),
	RECEIVER_ID NUMBER(10),
	DATE_SENT TIMESTAMP,
	CONSTRAINT FK_SENDER FOREIGN KEY (SENDER_ID) REFERENCES USERS (USER_ID),
	CONSTRAINT FK_RECEIVER FOREIGN KEY (RECEIVER_ID) REFERENCES USERS (USER_ID)
);

START facespace_test_data